"""Create complete model with minimum fields

Revision ID: 4402f107dfbf
Revises: 4a99a899b215
Create Date: 2023-08-29 19:40:04.482368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4402f107dfbf'
down_revision: Union[str, None] = '4a99a899b215'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('PositionTitle', sa.String(), nullable=True))
    op.add_column('jobs', sa.Column('PositionURI', sa.String(), nullable=True))
    op.add_column('jobs', sa.Column('PositionLocation', sa.JSON(), nullable=True))
    op.add_column('jobs', sa.Column('PositionRemuneration', sa.JSON(), nullable=True))
    op.drop_column('jobs', 'location')
    op.drop_column('jobs', 'jobname')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('jobname', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('jobs', sa.Column('location', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('jobs', 'PositionRemuneration')
    op.drop_column('jobs', 'PositionLocation')
    op.drop_column('jobs', 'PositionURI')
    op.drop_column('jobs', 'PositionTitle')
    # ### end Alembic commands ###
