"""Add missing field RemoteIndicator

Revision ID: d89f010675e0
Revises: 4402f107dfbf
Create Date: 2023-08-29 19:46:07.445261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd89f010675e0'
down_revision: Union[str, None] = '4402f107dfbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('RemoteIndicator', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'RemoteIndicator')
    # ### end Alembic commands ###
